window.__BAKED_JSREPL_BUILD__ = true;
(function(){var n,k,l,o,r,p,s,t,q=[].slice,j=function(h,a){return function(){return h.apply(a,arguments)}},v={}.hasOwnProperty,u=function(h,a){function c(){this.constructor=h}for(var b in a)v.call(a,b)&&(h[b]=a[b]);c.prototype=a.prototype;h.prototype=new c;h.__super__=a.prototype;return h};k=document.getElementById("jsrepl-script");if(k!=null)n=k.src.split("/").slice(0,-1).join("/"),r=""+n+"/sandbox.html";else throw Error('JSREPL script element cannot be found. Make sure you have the ID "jsrepl-script" on it.');
o=function(){function h(){var a,c=this;a=function(){c.head=document.getElementsByTagName("head")[0];return c.body=document.getElementsByTagName("body")[0]};a();this.loadfns=[a];window.onload=function(){var b,a,e,d,f;d=c.loadfns;f=[];for(a=0,e=d.length;a<e;a++)b=d[a],f.push(b());return f};this.iframe=null}h.prototype._appendChild=function(a,c){var b,g=this;b=function(){return g[a].appendChild(c)};return this[a]!=null?b():this.loadfns.push(b)};h.prototype.createSandbox=function(a){var c=this;this.iframe!=
null&&this.body.removeChild(this.iframe);this.iframe=document.createElement("iframe");this.iframe.src=r;this.iframe.style.display="none";this.iframe.onload=function(){return a(c.iframe.contentWindow)};return this._appendChild("body",this.iframe)};return h}();k=function(){function h(){this.listeners={}}h.prototype.makeArray=function(a){Object.prototype.toString.call(a)!=="[object Array]"&&(a=[a]);return a};h.prototype.on=function(a,c){var b,g,e,d;if(typeof c==="function"){a=this.makeArray(a);d=[];
for(g=0,e=a.length;g<e;g++)b=a[g],this.listeners[b]==null?d.push(this.listeners[b]=[c]):d.push(this.listeners[b].push(c));return d}};h.prototype.off=function(a,c){var b,g,e,d,f,a=this.makeArray(a);f=[];for(e=0,d=a.length;e<d;e++)b=a[e],g=this.listeners[b],g!=null&&(c!=null?(b=g.indexOf(c),b>-1?f.push(g.splice(b,1)):f.push(void 0)):f.push(this.listeners[b]=[]));return f};h.prototype.fire=function(a,c){var b,g,e,d,c=this.makeArray(c);g=this.listeners[a];if(g!=null){c.push(a);var f;f=[];for(e=0,d=g.length;e<
d;e++)b=g[e],f.push(b);d=[];for(g=0,e=f.length;g<e;g++)b=f[g],d.push(b.apply(this,c));return d}};h.prototype.once=function(a,c){var b,g,e,d,f,h=this,a=this.makeArray(a);b=function(){var g,e,f,d;g=1<=arguments.length?q.call(arguments,0):[];for(f=0,d=a.length;f<d;f++)e=a[f],h.off(e,b);return c.apply(null,g)};f=[];for(e=0,d=a.length;e<d;e++)g=a[e],f.push(this.on(g,b));return f};return h}();t="Worker"in window;p=function(h){function a(c,b,a){var e;this.input_server=b;a==null&&(a={});this.onmsg=j(this.onmsg,
this);var d,f,h;h=[];for(d=0,f=c.length;d<f;d++)b=c[d],h.push(n+"/"+b);this.baseScripts=h;this.loader=new o;for(e in a)c=a[e],typeof c==="function"&&(a[e]=[c]);this.listeners=a}u(a,h);a.prototype.onmsg=function(a){var b;try{return b=JSON.parse(a.data),this.fire(b.type,[b.data])}catch(g){}};a.prototype.load=function(a,b){var g,e,d,f=this;b==null&&(b=true);g=this.baseScripts.concat(a);e=g.shift();this.worker!=null&&this.kill();d=function(){f.post({type:"importScripts",data:g});if(f.input_server!=null)return f.post({type:"set_input_server",
data:f.input_server})};window.removeEventListener("message",this.onmsg,false);return!t||!b?this.loader.createSandbox(function(a){f.worker=a;f.workerIsIframe=true;window.addEventListener("message",f.onmsg,false);return d()}):(this.worker=new Worker(e),this.workerIsIframe=false,this.worker.addEventListener("message",this.onmsg,false),d())};a.prototype.post=function(a){a=JSON.stringify(a);return this.workerIsIframe?this.worker.postMessage(a,"*"):this.worker.postMessage(a)};a.prototype.kill=function(){var a;
typeof(a=this.worker).terminate==="function"&&a.terminate();if(this.loader.body!=null&&this.loader.iframe)return this.loader.body.removeChild(this.loader.iframe),delete this.loader.iframe};return a}(k);s=function(){var h,a,c;h={firefox_3:/firefox\/3/i,opera:/opera/i,chrome:/chrome/i};for(a in h)if(c=h[a],c.test(window.navigator.userAgent))return a}();l=function(h){function a(c){var b,g,e,d,f,h,i,m=this;b=c!=null?c:{};i=b.result;c=b.error;e=b.input;f=b.output;h=b.progress;this.timeout=b.timeout;d=
b.input_server;this.getLangConfig=j(this.getLangConfig,this);this.rawEval=j(this.rawEval,this);this.eval=j(this.eval,this);this.checkLineEnd=j(this.checkLineEnd,this);this.loadLanguage=j(this.loadLanguage,this);this.off=j(this.off,this);this.on=j(this.on,this);a.__super__.constructor.call(this);window.openDatabase!=null&&(g=openDatabase("replit_input","1.0","Emscripted input",1024),g.transaction(function(a){a.executeSql("DROP TABLE IF EXISTS input");return a.executeSql("CREATE TABLE input (text)")}));
d==null&&(d={});d.input_id=Math.floor(Math.random()*9007199254740992)+1;this.lang=null;this.on("input",e);b=["sandbox.js"];window.__BAKED_JSREPL_BUILD__||(b=b.concat(["util/polyfills.js","util/mtwister.js"]));this.sandbox=new p(b,d,{output:f,input:function(){return m.fire("input",function(a){return m.sandbox.post({type:"input.write",data:a})})},error:c,result:i,progress:h,db_input:function(){return m.fire("input",function(a){m.sandbox.fire("recieved_input",[a]);return g.transaction(function(b){return b.executeSql("INSERT INTO input (text) VALUES ('"+
a+"')",[])})})},server_input:function(){return m.fire("input",function(a){var b,c;m.sandbox.fire("recieved_input",[a]);b=(d.url||"/emscripten/input/")+d.input_id++;if(d.cors)if(c=new XMLHttpRequest,"withCredentials"in c)c.open("POST",b,true);else if(typeof XDomainRequest!=="undefined"&&XDomainRequest!==null)c=new XDomainRequest,c.open("POST",b);else throw Error("CORS not supported on your browser");else c=new XMLHttpRequest,c.open("POST",b,true);c.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
return c.send("input="+a)})}})}u(a,h);a.prototype.on=function(c,b){var g,e,d,f,c=this.makeArray(c);f=[];for(e=0,d=c.length;e<d;e++)g=c[e],g==="input"?f.push(a.__super__.on.call(this,"input",b)):f.push(this.sandbox.on(g,b));return f};a.prototype.off=function(c,b){var g,e,d,f,c=this.makeArray(c);f=[];for(e=0,d=c.length;e<d;e++)g=c[e],g==="input"?f.push(a.__super__.off.call(this,"input",b)):f.push(this.sandbox.off(g,b));return f};a.prototype.loadLanguage=function(c,b,g){var e,d;typeof b==="function"&&
(d=[b,void 0],g=d[0],b=d[1]);if(a.prototype.Languages.prototype[c]==null)throw Error("Language "+c+" not supported.");this.current_lang_name=c;this.lang=a.prototype.Languages.prototype[c];if(g!=null)this.sandbox.once("ready",g);return this.sandbox.load(function(){var a,b,c,d;c=this.lang.scripts;d=[];for(a=0,b=c.length;a<b;a++)e=c[a],typeof e==="object"?d.push(e[s]||e["default"]):d.push(e);return d}.call(this).concat([this.lang.engine]),b)};a.prototype.checkLineEnd=function(a,b){return/\n\s*$/.test(a)?
b(false):(this.sandbox.once("indent",b),this.sandbox.post({type:"getNextLineIndent",data:a}))};a.prototype.eval=function(a,b){var g,e,d,f,h,i=this;!this.sandbox.workerIsIframe&&this.timeout!=null&&this.timeout.time&&this.timeout.callback&&(f=null,e=function(){i.sandbox.fire("timeout");return i.timeout.callback()?h():f=setTimeout(e,i.timeout.time)},f=setTimeout(e,this.timeout.time),d=function(){var a,b;2<=arguments.length?q.call(arguments,0,b=arguments.length-1):b=0;a=arguments[b++];clearTimeout(f);
if(a==="input")return i.once("recieved_input",function(){return f=setTimeout(e,i.timeout.time)}),g()},g=function(){return i.once(["result","error","input"],d)},h=function(){return i.off(["result","error","input"],d)},g());if(typeof b==="function")this.once(["result","error"],function(){var a,c,d;a=2<=arguments.length?q.call(arguments,0,d=arguments.length-1):(d=0,[]);c=arguments[d++];return c==="error"?b(a[0],null):b(null,a[0])});return this.sandbox.post({type:"engine.Eval",data:a})};a.prototype.rawEval=
function(a){return this.sandbox.post({type:"engine.RawEval",data:a})};a.prototype.getLangConfig=function(c){return a.prototype.Languages.prototype[c||this.current_lang_name]||null};return a}(k);l.prototype.Languages=function(){return function(){}}();l.prototype.__test__=function(){return function(){}}();l.prototype.__test__.prototype.Loader=o;l.prototype.__test__.prototype.EventEmitter=k;l.prototype.__test__.prototype.Sandbox=p;this.JSREPL=l}).call(this);
JSREPL.prototype.Languages.prototype={qbasic:{system_name:"qbasic",name:"Quick Basic",extension:"bas",matchings:[],scripts:[{"default":["engines/qbasic-default.js?51c9323b345b43ffe05ec7f31085391a"]}],includes:[],engine:"langs/qbasic/jsrepl_qbasic.js?ae41a0874dfb636eb10975d6ec5eddbc",minifier:"closure"},scheme:{system_name:"scheme",name:"Scheme",extension:"scm",matchings:[["(",")"],["[","]"]],scripts:[{"default":["engines/scheme-default.js?868d8696cb69d728f098a9422dd7ebb1"]}],includes:[],engine:"langs/scheme/jsrepl_scheme.js?170b06b3727e61b8db8db233fc2a7208",
minifier:"closure_es5"},apl:{system_name:"apl",name:"APL",extension:"apl",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/apl-default.js?76857c82b75bfee6ad62b33ae2379501"]}],includes:[],engine:"langs/apl/jsrepl_apl.js?3603387502bf32f8963a4a4ca42b5783",minifier:"yui"},javascript:{system_name:"javascript",name:"JavaScript",extension:"js",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/javascript-default.js?65bb444af09df5e0489cb4eeca585b60"]}],includes:[],
engine:"langs/javascript/jsrepl_js.js?046802f3495ec4f2ec9616196f05cf15",minifier:"closure"},coffeescript:{system_name:"coffeescript",name:"CoffeeScript",extension:"coffee",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/coffeescript-default.js?ab9b82ff8b85c40b4a19e8b20ea1c24d"]}],includes:[],engine:"langs/coffee-script/jsrepl_coffee.js?6eb6ea04ac6b9201c0cc7e0a61a9d2a2",minifier:"uglify"},brainfuck:{system_name:"brainfuck",name:"Brainfuck",extension:"bf",matchings:[["[","]"]],
scripts:[{"default":["engines/brainfuck-default.js?f8e0d9da103695e3dac38f57cb12f47e"]}],includes:[],engine:"langs/brainfuck/jsrepl_brainfuck.js?f806384a91575a341b08c5114a451c2b",minifier:"closure"},unlambda:{system_name:"unlambda",name:"Unlambda",extension:"unl",matchings:[],scripts:[{"default":["engines/unlambda-default.js?0369381fa06fb047411056537e3ccb85"]}],includes:[],engine:"langs/unlambda/jsrepl_unlambda.js?9a42f7e4f2bf2455356a0c3c21302bab",minifier:"closure"},lolcode:{system_name:"lolcode",
name:"LOLCODE",extension:"lol",matchings:[],scripts:[{"default":["engines/lolcode-default.js?0927fa6e73403519552c3f25999e2f10"]}],includes:[],engine:"langs/lolcode/jsrepl_lolcode.js?4e75b50f02c02c6293b44ff5e3983f6d",minifier:"closure"},kaffeine:{system_name:"kaffeine",name:"Kaffeine",extension:"k",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/kaffeine-default.js?6fe21e41ed5e18dac020a4edc84142e2"]}],includes:[],engine:"langs/kaffeine/jsrepl_kaffeine.js?ecba9b7668588bba7c54855a6b5e6235",
minifier:"closure"},move:{system_name:"move",name:"Move",extension:"mv",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/move-default.js?87029e7548fa64744a2ca9c39073a642"]}],includes:[],engine:"langs/move/jsrepl_move.js?f421274957af414892063d9535acb06b",minifier:"closure"},traceur:{system_name:"traceur",name:"Traceur",extension:"js",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/traceur-default.js?b1f3ea870721cd209b09878dd087f2a5"]}],includes:[],engine:"langs/traceur/jsrepl_traceur.js?25cd4e7afe892436ac650edc8d3b03c7",
minifier:"uglify"},emoticon:{system_name:"emoticon",name:"Emoticon",extension:"emo",matchings:[["(",")"]],scripts:[{"default":["engines/emoticon-default.js?2e4dc82265ccc34f4416c3fb63996796"]}],includes:[],engine:"langs/emoticon/jsrepl_emoticon.js?20f9542baddae3265a88ae3eeb664dc9",minifier:"closure"},bloop:{system_name:"bloop",name:"Bloop/Floop",extensions:"bloop",matchings:[],scripts:[{"default":["engines/bloop-default.js?f66e26592f9355978903c47a4d6eb311"]}],includes:[],engine:"langs/bloop/jsrepl_bloop.js?8e92bb724a4d6922eb39a8867ac46d5e",
minifier:"closure"},forth:{system_name:"forth",name:"Forth",extensions:"4th",matchings:[["(",")"],[":",";"]],scripts:[{"default":["engines/forth-default.js?7288e57d257b560de97aec80811d77d2"]}],includes:[],engine:"langs/forth/jsrepl_forth.js?a258c27eb20db0b8412e1414f9acbb1c",minifier:"closure"},lua:{system_name:"lua",name:"Lua",extension:"lua",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{"default":["engines/lua-default.js?4ac15699cc2f845dddf420ebb3061776"]}],includes:[],engine:"langs/lua/jsrepl_lua.js?cf636c282d7b447ecf9e744c6272d3c8",
minifier:"none",emscripted:true},python:{system_name:"python",name:"Python",extension:"py",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{opera:["engines/python-opera.js?e1362b71bb960a1ca785563c2ce53e0e"],"default":["engines/python-default.js?ef2d736f5e25e8420b10f4de315336e8"]}],includes:["extern/python/unclosured","extern/python/closured","extern/python/reloop-closured"],engine:"langs/python/jsrepl_python.js?e26d0c9aa0d213a081d20d5d241b14bf",minifier:"none",emscripted:true},ruby:{system_name:"ruby",
name:"Ruby",extension:"rb",matchings:[["(",")"],["[","]"],["{","}"]],scripts:[{opera:["engines/ruby-opera.js?ecea667faea1fa3d23d99c3a6b95fd7d"],firefox_3:["engines/ruby-firefox_3.js?ecea667faea1fa3d23d99c3a6b95fd7d"],"default":["engines/ruby-default.js?57a1c7ba1c03ab0b434e5462e1e73ca3"]}],includes:["extern/ruby/dist/lib"],engine:"langs/ruby/jsrepl_ruby.js?02be9d3bb234201384a6e134dfcd66de",minifier:"none",emscripted:true},roy:{system_name:"roy",name:"Roy",extension:"roy",matchings:[["(",")"],["[",
"]"],["{","}"]],scripts:[{"default":["engines/roy-default.js?4c22d8dcd201c1035ddcf45449c1ebba"]}],includes:[],engine:"langs/roy/jsrepl_roy.js?16695bf9b295f11ae55bd05bb4351e5e",minifier:"closure"}};
